name: nanosquared
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.8
    - scipy>=1.6.3
    - numpy>=1.20.3
    - pyserial>=3.5
    - pandas>=1.2.4
    - wxpython>=4.1.1
    - comtypes>=1.1.8
    - matplotlib>=3.4.2
    - pyqt>=5.9.2
    - qt>=5.9.7