name: nanosquared
channels:
    - conda-forge
    - defaults
dependencies:
    - python>3.9,<3.10
    - scipy>=1.6.3,<=1.8
    - numpy>=1.20.3,<=1.22
    - pyserial=3.5
    - pandas>=1.2.4,<=1.4
    - wxpython=4.1.1
    - comtypes==1.1.8
    - pywin32>=228,<=303
    - pythonnet=2.5.2
    - pip
    - pip:
        - pyqt5>=5.15,<5.16
        - matplotlib>=3.4.2,<=3.5
        - msl-loadlib==0.9.0